title = "My Gitleaks Config"

[allowlist]
  paths = ["docs/", "README.md"]  # Ignore non-code files
  commits = []                    # No specific commits ignored
  regexes = ["dummy_api_key"]     # Known false positives

[[rules]]
description = "Generic API Key"
regex = '''(?i)apikey\s*[:=]\s*["']?[a-z0-9]{32,}["']?'''
tags = ["key", "API"]
