name: Centralized CI - .NET

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  build:
    uses: WahbaMousa-DevOps/CENTRALIZED-GITHUB-ACTIONS/.github/workflows/build.yml@main #called from the app repo, but runs inside the app repo context, not the central repo.
    with:
      language: dotnet
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  test:
    uses: WahbaMousa-DevOps/CENTRALIZED-GITHUB-ACTIONS/.github/workflows/test.yml@main
    with:
      language: dotnet

  scan:
    uses: WahbaMousa-DevOps/CENTRALIZED-GITHUB-ACTIONS/.github/workflows/scan.yml@main
    with:
      language: dotnet
    secrets:
      READ_PAT: ${{ secrets.READ_PAT }}
      SLACK_SECURITY_BOT_TOKEN: ${{ secrets.SLACK_SECURITY_BOT_TOKEN }} 

  trivy:
    uses: WahbaMousa-DevOps/CENTRALIZED-GITHUB-ACTIONS/.github/workflows/trivy.yml@main
    with:
      language: dotnet
        
  lint:
    uses: WahbaMousa-DevOps/CENTRALIZED-GITHUB-ACTIONS/.github/workflows/lint.yml@main
    with:
      language: dotnet
  sbom:
    uses: WahbaMousa-DevOps/CENTRALIZED-GITHUB-ACTIONS/.github/workflows/sbom.yml@main
    with:
      language: dotnet
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  notify:
    uses: WahbaMousa-DevOps/CENTRALIZED-GITHUB-ACTIONS/.github/workflows/notify.yml@main
    with:
      status: "Success"
      message: ".NET CI pipeline finished successfully."
    secrets:
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
